[2024-06-05T20:41:14.675+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T20:41:14.689+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2023-05-17T15:00:00+00:00 [queued]>
[2024-06-05T20:41:14.696+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2023-05-17T15:00:00+00:00 [queued]>
[2024-06-05T20:41:14.696+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-05T20:41:14.704+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2023-05-17 15:00:00+00:00
[2024-06-05T20:41:14.714+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=12871) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T20:41:14.715+0000] {standard_task_runner.py:63} INFO - Started process 12998 to run task
[2024-06-05T20:41:14.715+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2023-05-17T15:00:00+00:00', '--job-id', '1977', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpehcyqarr']
[2024-06-05T20:41:14.716+0000] {standard_task_runner.py:91} INFO - Job 1977: Subtask pipeline
[2024-06-05T20:41:14.745+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2023-05-17T15:00:00+00:00 [running]> on host d0ff8214a49e
[2024-06-05T20:41:14.793+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2023-05-17T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-17T15:00:00+00:00'
[2024-06-05T20:41:14.794+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T20:41:14.795+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T20:41:14.796+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/airflow_hw/modules/pipeline.py", line 73, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/train/homework.csv'
[2024-06-05T20:41:14.802+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2023-05-17T15:00:00+00:00, execution_date=20230517T150000, start_date=20240605T204114, end_date=20240605T204114
[2024-06-05T20:41:14.811+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1977 for task pipeline ([Errno 2] No such file or directory: './data/train/homework.csv'; 12998)
[2024-06-05T20:41:14.848+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T20:41:14.860+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T20:41:14.862+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
