[2024-06-07T18:08:28.916+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T18:08:28.926+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.predict manual__2024-06-07T18:08:07.700670+00:00 [queued]>
[2024-06-07T18:08:28.929+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.predict manual__2024-06-07T18:08:07.700670+00:00 [queued]>
[2024-06-07T18:08:28.929+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-07T18:08:28.936+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict> on 2024-06-07 18:08:07.700670+00:00
[2024-06-07T18:08:28.944+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=365) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T18:08:28.945+0000] {standard_task_runner.py:63} INFO - Started process 379 to run task
[2024-06-07T18:08:28.945+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'predict', 'manual__2024-06-07T18:08:07.700670+00:00', '--job-id', '2877', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpjyfjip5i']
[2024-06-07T18:08:28.946+0000] {standard_task_runner.py:91} INFO - Job 2877: Subtask predict
[2024-06-07T18:08:28.969+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.predict manual__2024-06-07T18:08:07.700670+00:00 [running]> on host 23149627dc8e
[2024-06-07T18:08:29.014+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2024-06-07T18:08:07.700670+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-07T18:08:07.700670+00:00'
[2024-06-07T18:08:29.014+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T18:08:29.015+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T18:08:29.015+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/airflow_hw/modules/predict.py", line 27, in predict
    model_filename = os.listdir(f'{path}/data/models/')[-1]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/models/'
[2024-06-07T18:08:29.019+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=predict, run_id=manual__2024-06-07T18:08:07.700670+00:00, execution_date=20240607T180807, start_date=20240607T180828, end_date=20240607T180829
[2024-06-07T18:08:29.026+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2877 for task predict ([Errno 2] No such file or directory: './data/models/'; 379)
[2024-06-07T18:08:29.038+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-07T18:08:29.047+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-07T18:08:29.048+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
