[2024-06-05T16:39:27.729+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T16:39:27.752+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2024-01-09T15:00:00+00:00 [queued]>
[2024-06-05T16:39:27.759+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2024-01-09T15:00:00+00:00 [queued]>
[2024-06-05T16:39:27.759+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T16:39:27.785+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2024-01-09 15:00:00+00:00
[2024-06-05T16:39:27.799+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=14744) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T16:39:27.802+0000] {standard_task_runner.py:63} INFO - Started process 14758 to run task
[2024-06-05T16:39:27.814+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2024-01-09T15:00:00+00:00', '--job-id', '1102', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpfurco1ty']
[2024-06-05T16:39:27.814+0000] {standard_task_runner.py:91} INFO - Job 1102: Subtask pipeline
[2024-06-05T16:39:27.848+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2024-01-09T15:00:00+00:00 [running]> on host ece5ff154bbf
[2024-06-05T16:39:27.935+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-01-09T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-09T15:00:00+00:00'
[2024-06-05T16:39:27.936+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T16:39:28.911+0000] {pipeline.py:116} INFO - model: LogisticRegression, acc_mean: 0.7591, acc_std: 0.0075
[2024-06-05T16:39:49.692+0000] {pipeline.py:116} INFO - model: RandomForestClassifier, acc_mean: 0.7778, acc_std: 0.0048
[2024-06-05T16:40:00.034+0000] {pipeline.py:116} INFO - model: SVC, acc_mean: 0.7871, acc_std: 0.0042
[2024-06-05T16:40:00.034+0000] {pipeline.py:121} INFO - best model: SVC, accuracy: 0.7871
[2024-06-05T16:40:02.246+0000] {pipeline.py:129} INFO - Model is saved as /home/***/***_hw/data/models/cars_pipe_202406051640.pkl
[2024-06-05T16:40:02.248+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T16:40:02.248+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T16:40:02.252+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2024-01-09T15:00:00+00:00, execution_date=20240109T150000, start_date=20240605T163927, end_date=20240605T164002
[2024-06-05T16:40:02.306+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T16:40:02.317+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T16:40:02.319+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-05T20:58:11.801+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T20:58:11.817+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2024-01-09T15:00:00+00:00 [queued]>
[2024-06-05T20:58:11.823+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2024-01-09T15:00:00+00:00 [queued]>
[2024-06-05T20:58:11.823+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T20:58:11.831+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2024-01-09 15:00:00+00:00
[2024-06-05T20:58:11.840+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=20034) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T20:58:11.841+0000] {standard_task_runner.py:63} INFO - Started process 20180 to run task
[2024-06-05T20:58:11.841+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2024-01-09T15:00:00+00:00', '--job-id', '2436', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmp4b1j9e8b']
[2024-06-05T20:58:11.842+0000] {standard_task_runner.py:91} INFO - Job 2436: Subtask pipeline
[2024-06-05T20:58:11.875+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2024-01-09T15:00:00+00:00 [running]> on host d0ff8214a49e
[2024-06-05T20:58:11.931+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-01-09T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-09T15:00:00+00:00'
[2024-06-05T20:58:11.932+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T20:58:11.933+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T20:58:11.933+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/airflow_hw/modules/pipeline.py", line 73, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/train/homework.csv'
[2024-06-05T20:58:11.939+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2024-01-09T15:00:00+00:00, execution_date=20240109T150000, start_date=20240605T205811, end_date=20240605T205811
[2024-06-05T20:58:11.949+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2436 for task pipeline ([Errno 2] No such file or directory: './data/train/homework.csv'; 20180)
[2024-06-05T20:58:11.974+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T20:58:11.987+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T20:58:11.989+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
